[package]
name = "api-error-derive"
version = "0.1.0"
description = "Procedural macros for the api-error crate"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", default-features = false, features = [
    "derive",
    "parsing",
    "printing",
    "proc-macro",
] }

quote = "1"
proc-macro2 = "1"

[dev-dependencies]
syn = { version = "2", default-features = false, features = ["extra-traits"] }

[features]
axum = []
